##### Template Figure Analysis #####
##### authored by Tony Ingram #####

# This script analyzes large numbers of auto-generated template trajectory 
# figures. The purpose is to characterize the randomly generated figures 
# (pathlength, complexity, etc.) at the parameters set in TraceLab_params.py.

# rm(list = ls()) # clear work space
# rm(list=setdiff(ls(), "all_data")) # clear all but all_data (change name for this)
# graphics.off() # clear figures
# cat("\014") # clear console

# note that there will be everything but no .tlt in the autogenerated files.
# and .tlf files are large and verbose as they are used for generating figs
# within an experiment.
# this won't be a problem in importdata.R, as we will be analyzing 
# 